# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0UGzydWCNlcPmwONy_OSvf0qmSffGLN
"""

from collections import deque

class stack:
  def __init__(self):
    self.stkk=deque()
  def checker(self,data):
    vb=data[0]
    sp=len(self.stkk)
    if sp != 0:
      for t in range(0,sp):
        self.stkk.pop()

    if vb in "({[":
       for i in data:
         if i in "([{":
           self.stkk.append(i)
         elif i in ")]}":
           self.stkk.pop()
    elif vb in ")}]":
      self.stkk.append("wrongentery")

  def is_empty(self):
      return len(self.stkk)==0

node = stack()

node.checker("(a+b)")
print(node.is_empty())

node.checker("))}} a+b {{((")
print(node.is_empty())

node.checker("((a+b))")
print(node.is_empty())

node.checker("))")
print(node.is_empty())

node.checker("[a+b](x+2y){gg+kk}")
print(node.is_empty())

